<?php declare(strict_types=1); use App\Core\Csrf; require __DIR__.'/header.php'; ?>
<a class="back-link" href="/admin/<?= e($entity) ?>">← Voltar para <?= e($entity) ?></a><h1><?= $id?'Editar cadastro':'Novo cadastro' ?></h1><p class="admin-subtitle">As alterações salvas aparecem no site público conforme o status e a disponibilidade.</p>
<?php if($errors): ?><div class="admin-error" role="alert"><strong>Revise os campos abaixo.</strong><ul><?php foreach($errors as $key=>$message): ?><li><?= e(($config['fields'][$key][0]??ucfirst($key)).': '.$message) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="_csrf" value="<?= e(Csrf::token()) ?>"><div class="form-grid">
<?php foreach($config['fields'] as $key=>$field): [$label,$type]=$field;$value=$record[$key]??($type==='bool'?($id===null && $key!=='destaque'):($type==='integer'?'1':($key==='rotulo_preco'?'unidade':'')));if($type==='password')$value='';if(is_array($value))$value=''; ?>
<div class="form-field <?= $type==='textarea'?'wide':'' ?>"><label for="<?= e($key) ?>"><?= e($label) ?><?= ($field[3]??false)?' *':'' ?></label>
<?php if($type==='select'||$type==='category'): ?><select id="<?= e($key) ?>" name="<?= e($key) ?>" required><?php if($type==='category'): ?><option value="">Selecione</option><?php foreach($choices['categorias'] as $c): ?><option value="<?= (int)$c['id_categoria'] ?>" <?= (string)$value===(string)$c['id_categoria']?'selected':'' ?>><?= e($c['nome'].(!$c['ativa']?' (inativa)':'')) ?></option><?php endforeach ?><?php else: foreach($field[2] as $option): ?><option value="<?= e($option) ?>" <?= $value===$option?'selected':'' ?>><?= e($option) ?></option><?php endforeach;endif ?></select>
<?php elseif($type==='textarea'): ?><textarea id="<?= e($key) ?>" name="<?= e($key) ?>" rows="4" maxlength="<?= (int)$field[2] ?>"><?= e((string)$value) ?></textarea>
<?php elseif($type==='bool'): ?><input id="<?= e($key) ?>" name="<?= e($key) ?>" type="checkbox" value="1" <?= $value?'checked':'' ?>>
<?php else: ?><input id="<?= e($key) ?>" name="<?= e($key) ?>" type="<?= e(match($type){'password'=>'password','date'=>'date','url'=>'url','integer'=>'number',default=>'text'}) ?>" value="<?= e((string)$value) ?>" <?= ($field[3]??false)?'required':'' ?> <?= in_array($type,['text','phone','url','password'],true)?'maxlength="'.(int)$field[2].'"':'' ?> <?= $type==='integer'?'min="1" step="1"':'' ?> <?= $type==='password'?'autocomplete="new-password"':'' ?>><?php endif ?>
<?php if(isset($errors[$key])): ?><p class="field-error"><?= e($errors[$key]) ?></p><?php endif ?></div><?php endforeach ?>
<?php if($entity==='produtos'): ?><div class="form-field"><label for="sabores">Sabores (um por linha)</label><textarea id="sabores" name="sabores" rows="4"><?= e(is_string($record['sabores']??'')?$record['sabores']??'':'') ?></textarea></div><div class="form-field"><label for="tags">Tags e restrições (separadas por vírgula)</label><textarea id="tags" name="tags" rows="4"><?= e(is_string($record['tags']??'')?$record['tags']??'':'') ?></textarea><small>Ex.: vegano, sem lactose. Confirme as restrições com a cozinha.</small></div><?php endif ?>
<?php if(in_array($entity,['produtos','promocoes'],true)): foreach($entity==='produtos'?['unidades']:['unidades','produtos'] as $relation): $key=$relation==='unidades'?'id_unidade':'id_produto'; ?><fieldset class="form-field"><legend><?= $relation==='unidades'?'Unidades participantes / disponíveis':'Produtos participantes' ?></legend><div class="checkbox-list"><?php foreach($choices[$relation] as $choice): ?><label><input type="checkbox" name="<?= e($relation) ?>[]" value="<?= (int)$choice[$key] ?>" <?= in_array((int)$choice[$key],array_map('intval',is_array($record[$relation]??null)?$record[$relation]:[]),true)?'checked':'' ?>> <?= e($choice['nome']) ?></label><?php endforeach ?></div></fieldset><?php endforeach;endif ?>
<?php if(in_array($entity,['produtos','unidades'],true)): ?><div class="form-field"><label for="imagem">Imagem (JPEG, PNG ou WebP; até 5 MB)</label><input id="imagem" type="file" name="imagem" accept="image/jpeg,image/png,image/webp"><?php if(!empty($record['imagem']) && dd_imagem($record['imagem'])): ?><img class="upload-preview" alt="Imagem atual" src="<?= e($record['imagem']) ?>"><?php endif ?><small>Deixe vazio para manter a imagem atual.</small></div><?php endif ?>
<?php if($entity==='unidades'): ?><div class="form-field"><label for="pdf_url">Catálogo PDF (até 10 MB)</label><input id="pdf_url" type="file" name="pdf_url" accept="application/pdf"><small>O arquivo anterior só é removido após a gravação do novo catálogo.</small><?php if($id && !empty($record['pdf_url']) && !empty($record['ativa'])): ?><a href="/catalogos/<?= e($record['slug']) ?>/download">Baixar catálogo atual</a><?php endif ?></div><?php endif ?>
</div><div class="form-footer"><a class="btn" href="/admin/<?= e($entity) ?>">Cancelar</a><button class="btn btn-primary" type="submit">Salvar alterações</button></div></form><?php if($entity==='produtos'&&$id): ?><form method="post" action="/admin/produtos/<?= $id ?>/excluir" data-confirm="Desativar este produto e preservar seus vínculos?"><input type="hidden" name="_csrf" value="<?= e(Csrf::token()) ?>"><button class="btn btn-sm mt-4" type="submit">Arquivar produto</button></form><?php endif ?><?php require __DIR__.'/footer.php'; ?>
